spring:
  application:
    name: inventory-service

  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

server:
  port: 8082                    # orders=8081, inventory=8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
